baseURL = 'https://rosarioyui.github.io'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "PaperMod"
paginate = 5

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

pygmentsUseClasses = true
summaryLength = 0

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "ExampleSite"
description = "ExampleSite description"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "RosarioYui"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Home"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  Title = "Just for fun"
  subtitle = ""
  imageUrl = "/images/profile.jpg"
  imageTitle = "<title of image as alt>" # optional  

    [params.analytics.google]
    SiteVerificationTag = "XYZabc"

    [params.analytics.bing]
    SiteVerificationTag = "XYZabc"

    [params.analytics.yandex]
    SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  disabled = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  limit = 10
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "posts"
name = "posts"
url = "/posts"
weight = 1

[[menu.main]]
identifier = "categories"
name = "categories"
url = "categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "tags/"
weight = 20

[[menu.main]]
identifier = "search"
name = "search"
url = "search/"
weight = 30

[[menu.main]]
identifier = "about"
name = "about"
url = "about/"
weight = 40

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = false
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = ""
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    style = ""
    tabWidth = ""
    
# Algolia configuration

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = [
  "title",
  "summary",
  "date",
  "publishdate",
  "expirydate",
  "permalink"
]
params = [ "categories", "tags" ]

[outputs]
home = [ "HTML", "RSS", "JSON" ]
